# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iLKoiz_6MQnljz9Yzs_jHUfZKF0wax8F
"""

# Commented out IPython magic to ensure Python compatibility.
# %cd langchain-github-bot/

import os
import pickle

from langchain import PromptTemplate
from langchain.llms import OpenAI

def print_answer(msg):

    template = """
    I want you to read the following input and pick the tags from the provided list that best describe the input. You can pick multiple tags. You must pick at least one tag.

    Return your answer as a list of strings, where each string is a tag from the list. For example, if you want to pick the tags "A" and "B", you would return ["A", "B"].

    Input: {query}
    Possible tags: {tags}

    Tags:
    """

    prompt = PromptTemplate(
        input_variables=["query", "tags"],
        template=template,
    )

    # initialize the models
    openai = OpenAI(
        model_name="text-davinci-003",
        openai_api_key=os.environ["OPENAI_API_KEY"],
    )

    # prepare the prompt
    prompt = prompt.format(
        query=msg,
        tags=os.environ["tags"],
    )

    # generate the answer
    answer = openai(prompt)

    return answer

def run(msg):
    return print_answer(msg)


def setup(config):
    os.environ["OPENAI_API_KEY"] = config["OPENAI_API_KEY"]
    os.environ["tags"] = config["tags"]